version: "3"
services:
  frontend:
    build: ./ryugod
    image: ghcr.io/${GITHUB_REPOSITORY}/ryugod-frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

  backend:
    build: .
    image: ghcr.io/${GITHUB_REPOSITORY}/ryugod-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
